Repository omeryusufyagci/fast-music-remover, pull requests merged in 2024-10, with the labels that each got.

#19 Improvement: Refactor Flask Backend for Maintainability (Edited by maintainer)
  app.py
Labels: improvement, backend

#26 Feature: Add CommandBuilder interface for core
  MediaProcessor/CMakeLists.txt
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/AudioProcessor.h
  MediaProcessor/src/CommandBuilder.cpp
  MediaProcessor/src/CommandBuilder.h
  MediaProcessor/src/ICommandBuilder.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
  MediaProcessor/src/main.cpp
Labels: feature, core

#27 Refactor: Update core for standardized filepaths and command building
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/AudioProcessor.h
  MediaProcessor/src/CommandBuilder.cpp
  MediaProcessor/src/CommandBuilder.h
  MediaProcessor/src/ConfigManager.cpp
  MediaProcessor/src/ConfigManager.h
  MediaProcessor/src/ICommandBuilder.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
  MediaProcessor/src/VideoProcessor.cpp
  MediaProcessor/src/VideoProcessor.h
  MediaProcessor/src/main.cpp
  app.py
Labels: improvement, backend, core

#21 Improvement: Add Auto-Configuration for Thread Usage in MediaProcessor #5
  .clang-format
  MediaProcessor/CMakeLists.txt
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/AudioProcessor.h
  MediaProcessor/src/ConfigManager.cpp
  MediaProcessor/src/ConfigManager.h
  MediaProcessor/src/HardwareUtils.cpp
  MediaProcessor/src/HardwareUtils.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
  config.json
Labels: feature, hacktoberfest-accepted, core

#35 Add pre-commit hooks and workflows for build and formatting
  .flake8
  .github/workflows/build-mediaprocessor.yml
  .github/workflows/clang-format_check.yml
  .github/workflows/pep8-check.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  MediaProcessor/src/main.cpp
  app.py
  pyproject.toml
  requirements.txt
Labels: feature

#44 Add FFmpegSettingsManager to core
  MediaProcessor/CMakeLists.txt
  MediaProcessor/src/FFmpegSettingsManager.cpp
  MediaProcessor/src/FFmpegSettingsManager.h
Labels: feature, core

#47 Refactor AudioProcessor and add docs to core
  CONTRIBUTING.md
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/AudioProcessor.h
  MediaProcessor/src/CommandBuilder.h
  MediaProcessor/src/ConfigManager.h
  MediaProcessor/src/DeepFilterNetFFI.h
  MediaProcessor/src/FFmpegSettingsManager.h
  MediaProcessor/src/HardwareUtils.h
  MediaProcessor/src/ICommandBuilder.h
  MediaProcessor/src/Utils.h
  MediaProcessor/src/VideoProcessor.h
  MediaProcessor/src/main.cpp
Labels: documentation, refactor, core

#49 Add unit tests to core using Google Test
  .gitignore
  MediaProcessor/CMakeLists.txt
  MediaProcessor/cmake/src.cmake
  MediaProcessor/cmake/test.cmake
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/AudioProcessor.h
  MediaProcessor/src/ConfigManager.cpp
  MediaProcessor/src/ConfigManager.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
  MediaProcessor/tests/AudioProcessorTester.cpp
  MediaProcessor/tests/CommandBuilderTester.cpp
  MediaProcessor/tests/ConfigManagerTester.cpp
  MediaProcessor/tests/TestMedia/test_audio.wav
  MediaProcessor/tests/TestMedia/test_audio_processed.wav
  MediaProcessor/tests/TestMedia/test_video.mkv
  MediaProcessor/tests/TestMedia/test_video_processed.mp4
  MediaProcessor/tests/TestUtils.cpp
  MediaProcessor/tests/TestUtils.h
  MediaProcessor/tests/UtilsTester.cpp
  MediaProcessor/tests/VideoProcessorTester.cpp
  config.json
Labels: feature, testing, core

#50 Add Test Step to Core CI Pipeline
  .github/workflows/build-mediaprocessor.yml
  .github/workflows/build_test_and_format_core.yml
  .github/workflows/clang-format_check.yml
  .github/workflows/format_backend.yml
Labels: improvement, testing, core, CI

#42 Feature: Add DeepFilterCommandBuilder to MediaProcessor
  MediaProcessor/CMakeLists.txt
  MediaProcessor/cmake/src.cmake
  MediaProcessor/src/AudioProcessor.cpp
  MediaProcessor/src/ConfigManager.cpp
  MediaProcessor/src/DeepFilterCommandBuilder.cpp
  MediaProcessor/src/DeepFilterCommandBuilder.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
Labels: feature, iteration, core

#53 Refactor: Revise FFmpegSettingsManager's singleton behavior
  MediaProcessor/src/FFmpegSettingsManager.cpp
  MediaProcessor/src/FFmpegSettingsManager.h
Labels: improvement, refactor, core

#57 Add `FFmpegCommandBuilder` class (#51)
  MediaProcessor/src/CommandBuilder.cpp
  MediaProcessor/src/CommandBuilder.h
  MediaProcessor/src/FFmpegCommandBuilder.cpp
  MediaProcessor/src/FFmpegCommandBuilder.h
  MediaProcessor/src/FFmpegSettingsManager.cpp
  MediaProcessor/src/FFmpegSettingsManager.h
  MediaProcessor/src/ICommandBuilder.h
  MediaProcessor/src/Utils.cpp
  MediaProcessor/src/Utils.h
Labels: feature, core
